server:
  port: 8081
## Api related configurations
api:
  info:
    title: Resilience Demo API
    description: Resilience4j  implementation.
    version: 1.0.0
    terms-of-service: https://www.ippen-digital-media.de/impressum/
    contact:
      name: BI Team
      email: antonio.casado@ippen-digital.de
      url: https://www.ippen-digital-media.de/
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
  logging:
    enable: true
    url-patterns: "/*"
    requestIdParamName: CORRELATION_ID

## Api Doc related configurations
springdoc:
  swagger-ui:
    enabled: true
    path: /   # Redirect localhost:8080 to swagger-ui.html

## Database related configurations
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  h2:
    console:
      enabled:  true

# Resilience configurations
resilience4j:
  bulkhead:
    instances:
      userBulkheadService:
        maxWaitDuration: 100ms
        maxConcurrentCalls: 3
  circuitbreaker:
    instances:
      userCircuitBreakerCService:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      userRetryService:
        waitDuration: 200
        maxRetryAttempts: 3
  ratelimiter:
    instances:
      userRateLimiterService:
        limitForPeriod: 3
        limitRefreshPeriod: 60s
        timeoutDuration: 2s
  #        registerHealthIndicator: true
  #        eventConsumerBufferSize: 100
  timelimiter:
    configs:
      default:
        cancelRunningFuture: false
        timeoutDuration: 2s
    instances:
      userTimeLimiterService:
        baseConfig: default
#      backendB:
#        baseConfig: default
#        cancelRunningFuture: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always